### PR TITLE
align some inconsistencies with providing a goal

### PR DESCRIPTION
**Pull request by krugerk**
clean code

align some inconsistencies with providing a goal
to some view controllers that required one

See https://github.com/beeminder/BeeSwift/pull/481#issuecomment-2379771571

### CODE REVIEW

**Comment by theospears** [comment]
Could you update the PR to merge cleanly, now I have merged the test fixes in #481

**Review by theospears — APPROVED** [review]

**Comment by theospears** [comment]
Once again conflicting. Maybe consider using https://graphite.dev/ so you can open stacked PRs?

**Comment by krugerk** [comment]
> Once again conflicting.

_updated_

**Comment by krugerk** [comment]
> Maybe consider using https://graphite.dev/ so you can open stacked PRs?

Thanks for the tip. I have seen merge requests of yours referring to it.

**Pull request merged**
