### PR TITLE
segmentedControl for sorting goals on gallery

### PR DESCRIPTION
**Pull request by krugerk**
- allow sorting of the goals directly from the gallery
via the SegmentedControl
 - sort by preference is synced with one available in the
app settings
 - can combine filtering (by slug) with quick sort via segmentedControl

### CODE REVIEW

**Comment by krugerk** [comment]
In keeping up with the previous discussion on sorting goals (MR #58), where it was decided the three lists of goals should not share a common sort but rather the sorting of goals on the gallery should be closer to what one sees on the website, a segmented control has been introduced to allow "sorting by tapping column headers".
The sorting preference in the app settings and the selected segmented control are kept in sync and only used on the gallery.

(Unrelated but still noticeable are the flickering graphs, noted Bug #43.)

**Comment by krugerk** [comment]
GUI could use a bit of tweaking with dark appearance and/or on iOS 13 (with its different appearance for segmented controls -  for example the visible color behind the rounded corners of the segmented control)

**Comment by andrewpbrett** [comment]
I like this idea, I think we should get some user feedback about it. I want to get 5.7 released first and then we can put this into a 5.8beta and upload to TestFlight.

**Comment by krugerk** [comment]
If the sort pref only is for the gallery and we use this segmented control instead, then there need not be a separate screen just for picking the sort criteria.

**Pull request closed without merging**
