### PR TITLE
Changed Splash Screen and Placeholder Graph Images to match Login Page Dark Mode PR

### PR DESCRIPTION
**Pull request by emeraldfleur**
## Summary
Changed splash screen and placeholder / thumbnail graph images to match recent Login Page Dark Mode PR #561, for consistency. Fixes new issue #563.

Before:

Simulator Screenshot - iPhone 16 Pro - 2024-12-25 at 09 44 20

After:

Simulator Screenshot - iPhone 16 Pro - 2024-12-25 at 10 23 07

Subjectively, this seems to be better to match the other pending dark mode PR, #561. This also changes the placeholder image while waiting for an internet connection to load a graph, but due to being dark, your eye kind of glosses over it. Couldn't get a screenshot of placeholder image while loading graph because it went by so fast. 

## Validation
App launches on device (iOS 18.2 iPhone 13 Pro)  and in simulator. (iOS 18.2 iPhone 16 Pro) There are no code changes, merely .png asset swaps with no changes to the identifying .json files, and the new PNGs are the same dimensions as the old ones.

### CODE REVIEW

**Review by theospears — APPROVED** [review]
LGTM!

**Comment by theospears** [comment]
This change really makes me want dark-mode graphs. But not enough to perform atrocities like client-side image patching. We'll just have to wait for @dreeves to add support for this server side.

**Comment by theospears** [comment]
Ok, it turns out to be surprisingly hard to get the app build to notice that the images have changed. In future, let's avoid changing .png files, and instead add new files with new names, and update the config to point at them.

**Comment by krugerk** [comment]
> This change really makes me want dark-mode graphs. But not enough to perform atrocities like client-side image patching. We'll just have to wait for @dreeves to add support for this server side.

Others have called for having a table like listing and skipping the graphs altogether in the gallery. We could look into that, perhaps showing  something like what the ios 14 widgets MR presents.

**Comment by emerald-pham** [comment]
> Ok, it turns out to be surprisingly hard to get the app build to notice that the images have changed. In future, let's avoid changing .png files, and instead add new files with new names, and update the config to point at them.
> 
> 
> 
> See http://arsenkin.com/launch_screen_image_cache.html for more details.

Will do. Yeah, got used to clearing my cache before a build, oops 😅

**Comment by emeraldfleur** [comment]
I can add a new PR to change the file names so that it gets noticed on subsequent builds, if desired? Not a hard PR, and might count as an issue...

**Comment by theospears** [comment]
> I can add a new PR to change the file names so that it gets noticed on subsequent builds, if desired? Not a hard PR, and might count as an issue...

I would accept such a PR, but I don't see it as very important. It will fix itself over time as people restart their devices.

**Pull request merged**
