### PR TITLE
Changed Color of Beeminder Logo Text on Login Screen to White in Dark Mode

### LINKED ISSUE #150: Logo in dark mode is gray-on-black
```[tasklist]
### Desiderata
- [ ] Is the answer just "Beeminder doesn't support dark mode currently"?
```

signin dark on dark

Here is a screenshot, which actually is more legible now as a screenshot than the screen was in the app at the time (perhaps brightness was also very low).

## Cognata

* #55 
* #176

_**Verbata**: accessibility, contrast, dark mode, visibility,_

### PR DESCRIPTION
**Pull request by emeraldfleur**
## Summary

Changed color of Beeminder logo text on iOS app login screen to white in dark mode, by modifying relevant JSON to pull the dark mode .png file added in dark mode. Improves readability, and subjectively improves aesthetics. (Edit: Fixes #150)

Before:

(Screenshot taken on iOS 18.2, Beeminder iOS app version 6.7 (54), iPhone 13 Pro)

image
After:
image

Could not validate on hardware due to pending Apple Developer Account application, but literally just a flattened PNG image swap with same dimensions.

## Validation

Code compiles and app launches on iPadOS and iPhone 16 Pro simulators.

Could not validate on hardware due to pending Apple Developer Account application.

### CODE REVIEW

**Comment by emeraldfleur** [comment]
Even though it's strictly a configuration change, I would have assumed almost any non-documentation changes to work products would get fastlaned, no? Is there something I missed while submitting this PR, or do changes that might need to be fastlaned need to be manually thrown in there?

**Comment by krugerk** [comment]
@theospears is the current maintainer. Thus far this project has been primarily by one person, twice ( @andrewpbrett and now @theospears ) and I am not sure it was ever to the point it had well fleshed out procedures for bug reports or merge requests or even releases.

And MRs are currently all manual for @theospears (or theoretically @dreeves or similar) to review then merge.

**Comment by theospears** [comment]
I agree that we should be fastlaning these.

I'm a little surprised that this didn't run. In particular tests are setup to use "pull_request" rather than "pull_request_target" which means no particular access to the target repo should be needed. @emeraldfleur maybe check to see if your fork is configured to run actions, and has appropriate credit to do so.

Github does have some [rules about actions and first time contributors](https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/approving-workflow-runs-from-public-forks) but I would only expect these to apply to pull_request_target rules.

**Comment by theospears** [comment]
I've now merged #560 which means @emeraldfleur is no longer marked as a first time contributor, we can see if that helps.

**Comment by emeraldfleur** [comment]
Hello Theo,

This is a new account, but I've confirmed that my fork settings have 

- allow all actions and reusable workflows 

toggled on, probably not relevant, but 

- Read and write permissions 

is also toggled on.

Credits should be good as my repo is public.

This account @emeraldfleur is new to GitHub, I had just created it to separate my private work from my public work on this account. Because I hadn't had ANY merged pull requests before, it probably caught the GitHub spam filter that keeps first time accounts from having PRs fastlaned. I assume my next PR to this repo will auto fastlane, but in the meantime, I think the fastlane run will need to be approved and run by @theospears ? Not sure if there's anything more I can do on my end, but let me know, please!

Thank you.

**Comment by krugerk** [comment]
> I've now merged #560 which means @emeraldfleur is no longer marked as a first time contributor, we can see if that helps.

When I check to see if the checks for this MR, GitHub shows me a message that contains the link to https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/approving-workflow-runs-from-public-forks .

**Comment by krugerk** [comment]
> I agree that we should be fastlaning these.
> 
> 
> 
> I'm a little surprised that this didn't run. In particular tests are setup to use "pull_request" rather than "pull_request_target" which means no particular access to the target repo should be needed. @emeraldfleur maybe check to see if your fork is configured to run actions, and has appropriate credit to do so.
> 
> 
> 
> Github does have some [rules about actions and first time contributors](https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/approving-workflow-runs-from-public-forks) but I would only expect these to apply to pull_request_target rules.

I understood the link you posted to mean the opposite: pull_request requires approval especially for first time contributors.

**Comment by theospears** [comment]
Ok, I found the approve button! For future reference, it was on the 'Actions' tab for the repo, rather than on this PR

**Comment by krugerk** [comment]
Ctrl S in the simulator saves a screenshot of the simulator 😉

**Comment by emeraldfleur** [comment]
> Ctrl S in the simulator saves a screenshot of the simulator 😉

Thanks 😅 I'm still a novice, so I'll take any advice. Feel free to let me know if I do anything wrong!

**Comment by theospears** [comment]
This is definitely an improvement over the status quo, so we could merge as-is. One follow-up option would be to also switch to our new shiny dark-mode bee. (See `BeeSwift/Images/AppIcon`).

image

**Comment by krugerk** [comment]
I agree this shiny new dark mode bee looks better than the current image used on the sign in screen.

**Comment by dreeves** [comment]
No branding concerns! Yellow infinibee looks great. <3

**Comment by emeraldfleur** [comment]
Good day,

Suggested edit by theospars implemented into fork's branch. I wish github would let me rebase properly (unless I'm missing something) to clean up the commit history (is there only merges on here?) but, whatever. Just don't want upstream to get messy from my fork. 

Here is a screenshot in dark mode, iPhone 16 Pro, iOS 18.2.

Simulator Screenshot - iPhone 16 Pro - 2024-12-25 at 09 44 40

We've also passed fastlane, so looks like we're ready to go, unless there's anything I need to do on my fork to get it nicer? Should I have not merged the documentation change into this darkmode branch on my fork?...

Thanks all.

**Comment by krugerk** [comment]
> I wish github would let me rebase properly (unless I'm missing something) to clean up the commit history (is there only merges on here?) but, whatever.

You mean the master branch on your account's fork? I usually keep mine no further ahead than the upstream mainline (so beeminder/BeeSwift master in this case) and make branches for any changes, either fixes or features.

You can also branch from upstream mainline and then when you create the branch you push it to your repository (fork, where you can make branches) and then make the MR from there to beeminder/BeeSwift master.
Of course you can also reset your master branch to anything, including the current upstream master commit (and history).

**Comment by theospears** [comment]
> I wish github would let me rebase properly (unless I'm missing something) to clean up the commit history (is there only merges on here?) but, whatever. Just don't want upstream to get messy from my fork.

The convention on this repo is to squash-merge PRs (collapsing all commits in the PR into a single commit upstream), so while I'm a fan of clean commit history, you don't need to worry about your PR commit history making upstream messy.

**Review by theospears — APPROVED** [review]
Looks good to me!

**Pull request merged**
