### PR TITLE
Removed license visual badge from top of README.md

### PR DESCRIPTION
**Pull request by emeraldfleur**
# Summary

Removed license visual badge from top of README.md.

Before:

image

After:

image

## Validation

N/A, as there is no executable code, and the markdown renders correctly on the branch, as shown in the above screenshot.

# Initial PR

~~## Summary~~

~~Fixed broken link and incorrect license display. This fixes issue #565.~~

~~Before:~~

image

~~After:~~

image

### CODE REVIEW

**Comment by theospears** [comment]
Thanks for opening this PR!

So, I spent about 15 minutes trying to work out if there is a consensus around company logos and trademarks with respect to the MIT license. My main takeaways were:
1. I am not a copyright lawyer
2. Lots of companies MIT license their code while still asserting trademarks (see e.g. Visual Studio Code)
3. The Beeminder name is likely a trademark. The bee logo is likely also a trademark, but _are also likely protected by copyright, and licensing them under MIT would reduce those copyright protections_.
5. See (1).

On the basis of this, I don't think it is appropriate to relicense everything in the repo under MIT, and I don't think it's appropriate to have the MIT badge when not everything in the repo is under MIT. Also copyright/trademark/etc is just not a can of worms I want to open up or have people spend further time or energy on at this time. 

I agree the undetected license badge is kinda ugly, but suggest we instead just remove it as suggested in #205.

**Comment by emeraldfleur** [comment]
Per suggestion, deleted license tag in this branch. (And started cleaning up my fork. Thanks for all of the suggestions!)

Now README.md looks like the following on this PR's branch.

image

**Comment by theospears** [comment]
Thanks for following up, the change here looks good. Could you update the title and description of the PR to match the latest version?

**Comment by emeraldfleur** [comment]
> Thanks for following up, the change here looks good. Could you update the title and description of the PR to match the latest version?

Done, thank you.

**Review by theospears — APPROVED** [review]

**Pull request merged**
